path: pages/settings/widgets/tool_settings_section.dart
start_line: 1335
end_line: 1431
code: "const languageMap = {\n      // 中文系列\n      'zh': '中文',\n      'zh-CN': '中文\
  \ (简体)',\n      'zh-TW': '中文 (繁体)',\n      'zh-HK': '中文 (香港)',\n      'zh-SG': '中文\
  \ (新加坡)',\n\n      // 英语系列\n      'en': '英语',\n      'en-US': '英语 (美国)',\n     \
  \ 'en-GB': '英语 (英国)',\n      'en-AU': '英语 (澳大利亚)',\n      'en-CA': '英语 (加拿大)',\n\
  \      'en-IN': '英语 (印度)',\n\n      // 日语\n      'ja': '日语',\n      'ja-JP': '日语',\n\
  \n      // 韩语\n      'ko': '韩语',\n      'ko-KR': '韩语',\n\n      // 欧洲语言\n      'fr':\
  \ '法语',\n      'fr-FR': '法语 (法国)',\n      'fr-CA': '法语 (加拿大)',\n      'de': '德语',\n\
  \      'de-DE': '德语',\n      'es': '西班牙语',\n      'es-ES': '西班牙语 (西班牙)',\n     \
  \ 'es-MX': '西班牙语 (墨西哥)',\n      'it': '意大利语',\n      'it-IT': '意大利语',\n      'pt':\
  \ '葡萄牙语',\n      'pt-BR': '葡萄牙语 (巴西)',\n      'pt-PT': '葡萄牙语 (葡萄牙)',\n      'ru':\
  \ '俄语',\n      'ru-RU': '俄语',\n      'nl': '荷兰语',\n      'nl-NL': '荷兰语',\n\n   \
  \   // 北欧语言\n      'sv': '瑞典语',\n      'sv-SE': '瑞典语',\n      'da': '丹麦语',\n   \
  \   'da-DK': '丹麦语',\n      'no': '挪威语',\n      'no-NO': '挪威语',\n      'fi': '芬兰语',\n\
  \      'fi-FI': '芬兰语',\n\n      // 东欧语言\n      'pl': '波兰语',\n      'pl-PL': '波兰语',\n\
  \      'cs': '捷克语',\n      'cs-CZ': '捷克语',\n      'hu': '匈牙利语',\n      'hu-HU':\
  \ '匈牙利语',\n      'ro': '罗马尼亚语',\n      'ro-RO': '罗马尼亚语',\n      'bg': '保加利亚语',\n\
  \      'bg-BG': '保加利亚语',\n      'hr': '克罗地亚语',\n      'hr-HR': '克罗地亚语',\n      'sk':\
  \ '斯洛伐克语',\n      'sk-SK': '斯洛伐克语',\n      'sl': '斯洛文尼亚语',\n      'sl-SI': '斯洛文尼亚语',\n\
  \      'et': '爱沙尼亚语',\n      'et-EE': '爱沙尼亚语',\n      'lv': '拉脱维亚语',\n      'lv-LV':\
  \ '拉脱维亚语',\n      'lt': '立陶宛语',\n      'lt-LT': '立陶宛语',\n\n      // 其他语言\n     \
  \ 'ar': '阿拉伯语',\n      'ar-SA': '阿拉伯语',\n      'th': '泰语',\n      'th-TH': '泰语',\n\
  \      'vi': '越南语',\n      'vi-VN': '越南语',\n      'hi': '印地语',\n      'hi-IN': '印地语',\n\
  \      'tr': '土耳其语',\n      'tr-TR': '土耳其语',\n      'he': '希伯来语',\n      'he-IL':\
  \ '希伯来语',\n      'id': '印尼语',\n      'id-ID': '印尼语',\n      'ms': '马来语',\n     \
  \ 'ms-MY': '马来语',\n      'tl': '菲律宾语',\n      'tl-PH': '菲律宾语',\n    };"
